linterのエラーを修正したい
orukRed/tyranosyntax pull request #205
Opened 2024-08-11 12:54 UTC by orukRed

Fixes #203

runTest.ts修正

TODO:他にもlinter適用した感じにフォーマットして動作確認できたタイミングでdraftからPRに変更する

2024-08-18 10:41 UTC, orukRed commented
@botamochi0x12 
Linter適用しました。
デフォルトの設定のままでエラー出た箇所を修正しています。

2024-08-18 14:33 UTC, botamochi0x12 commented on src/subscriptions/TyranoJumpProvider.ts
> +    const enableJumpTags = [
```suggestion
    const TAGS_TO_JUMP = [ 
```

2024-08-18 14:42 UTC, botamochi0x12 requested changes
`const` が `let` に戻っていたり、変数が戻っていたりするので
おそらく merge での選び間違いだと思います 🤔 （参照： #204 ）

お手数ですが、これで間違いなければコメントください 🙏 
Approve をお返しいたします

2024-08-18 14:42 UTC, botamochi0x12 commented on src/subscriptions/TyranoJumpProvider.ts
> +    const enableJumpTags = [
おそらく `merge` での選び間違いです（参照： #204 ）

```suggestion
    const TAGS_TO_JUMP = [ 
```

2024-08-18 14:42 UTC, botamochi0x12 commented on src/subscriptions/TyranoJumpProvider.ts
> +            jumpTagObject[tagName] = tags[tagName][paramName].path;
おそらく merge での選び間違いです（参照： #204 ）
```suggestion
    // TyranoScript syntax.tag.parameterから、{"tagName":"Path"}の形のObjectを作成
    const tagsByName: TagsByName = await vscode.workspace
      .getConfiguration()
      .get("TyranoScript syntax.tag.parameter")!;
    for (const [tagName, tag] of Object.entries(tagsByName)) {
      for (const param of Object.values(tag)) {
        const types = [...param.type]; // NOTE: Every `param.type` is an array, not a string
        for (const type of types) {
          if (TAGS_TO_JUMP.includes(type)) {
            jumpTagObject[tagName] = param.path;
```

2024-08-19 00:19 UTC, orukRed commented on src/subscriptions/TyranoJumpProvider.ts
> +    const enableJumpTags = [
ご指摘ありがとうございます。 🙇 
すみません、おっしゃる通り選び間違いでした 🙏

2024-08-20 01:50 UTC, botamochi0x12 approved these changes
変更いただきありがとうございました 🎉 
確認しましたので Approve します 🚀 

（行末に気づいてしまったので1コミットだけ追加しました 🙇 ）

2024-08-20 14:38 UTC, orukRed commented
ありがとうございます。
マージします！

2024-08-20 14:38 UTC, merged